INTERSECTION_COLOR = "red"
END_COLOR = "blue"
CORNER_COLOR = "yellow"
COMPONENT_COLOR = "green"
CONNECTION_COLOR = "pink"
OTHER_NODE_COLOR = "white"

OTHER_EDGE_COLOR = "green"

FOREGROUND = 0
BACKGROUND = 255

CLASS_NAMES = ['capacitor', 'ground', 'inductor', 'resistor']

INTERSECTION_COMBINATION_DIST = 3
